# Generated by Django 5.2.8 on 2025-12-29 17:08

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=20)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('school_id', models.IntegerField(blank=True, null=True)),
                ('card_no', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('class_name', models.TextField(blank=True, null=True)),
                ('section_name', models.TextField(blank=True, null=True)),
                ('semester_id', models.IntegerField(blank=True, null=True)),
                ('lecture_no', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.CharField(default=attendance.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=80)),
                ('rtsp_port', models.PositiveIntegerField(default=554)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('rtsp_url', models.CharField(blank=True, max_length=255, null=True)),
                ('snapshot_url', models.CharField(blank=True, max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('supports_ptz', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(blank=True, null=True)),
                ('uid', models.IntegerField(unique=True)),
                ('card_no', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('class_name', models.TextField(blank=True, null=True)),
                ('section_name', models.TextField(blank=True, null=True)),
                ('semester_id', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(blank=True, null=True)),
                ('uid', models.IntegerField(unique=True)),
                ('card_no', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('class_name', models.TextField(blank=True, null=True)),
                ('section_name', models.TextField(blank=True, null=True)),
                ('semester_id', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
