# Generated by Django 5.2.8 on 2025-12-08 16:19

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.CharField(default=attendance.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.CharField(default=attendance.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=80)),
                ('rtsp_port', models.PositiveIntegerField(default=554)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('rtsp_url', models.CharField(blank=True, max_length=255, null=True)),
                ('snapshot_url', models.CharField(blank=True, max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('supports_ptz', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='attendance.college')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.CharField(default=attendance.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='attendance.college')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(default=attendance.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attendance.program')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('program', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(default=attendance.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='attendance.college')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.CharField(default=attendance.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('year_number', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='attendance.program')),
            ],
            options={
                'ordering': ['year_number'],
                'unique_together': {('program', 'year_number')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.CharField(default=attendance.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=20)),
                ('order_number', models.PositiveIntegerField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='attendance.year')),
            ],
            options={
                'ordering': ['order_number'],
                'unique_together': {('year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(default=attendance.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('section_number', models.CharField(max_length=10)),
                ('instructor', models.CharField(blank=True, max_length=200)),
                ('schedule', models.CharField(blank=True, max_length=200)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='attendance.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='attendance.semester')),
            ],
            options={
                'ordering': ['course', 'section_number'],
                'unique_together': {('course', 'semester', 'section_number')},
            },
        ),
    ]
