# Generated by Django 5.2.8 on 2025-12-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_college_camera_program_course_teacher_year_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/photos/'),
        ),
    ]
